# Generated by Django 6.0.2 on 2026-02-11 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinic_name', models.CharField(max_length=255)),
                ('cnpj', models.CharField(max_length=20, unique=True)),
                ('responsible_pet_owner', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf_owner', models.CharField(max_length=14, unique=True)),
                ('owner_name', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine_name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_name', models.CharField(default='', max_length=255)),
                ('pet_breed', models.CharField(default='', max_length=255)),
                ('pet_age', models.IntegerField(default=0)),
                ('owner_pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to='vacinacao.owner')),
            ],
        ),
        migrations.CreateModel(
            name='VaccinationPetRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine_name', models.CharField(default='', max_length=255)),
                ('vaccination_date', models.DateField()),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccination', to='vacinacao.pet')),
            ],
            options={
                'unique_together': {('pet', 'vaccine_name', 'vaccination_date')},
            },
        ),
        migrations.CreateModel(
            name='VaccineStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine_name', models.CharField(default='', max_length=255)),
                ('quantity', models.IntegerField(default=0)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='vacinacao.clinic')),
            ],
            options={
                'unique_together': {('vaccine_name', 'clinic')},
            },
        ),
    ]
