# Generated by Django 5.2.11 on 2026-02-11 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacinacao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='vaccinationpetrecord',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='vaccinationpetrecord',
            name='vaccine_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacinacao.vaccine'),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='vaccinestock',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='vaccinestock',
            name='vaccine_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacinacao.vaccine'),
        ),
    ]
