# Generated by Django 5.2.11 on 2026-02-12 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacinacao', '0002_alter_clinic_id_alter_owner_id_alter_pet_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vaccinationpetrecord',
            old_name='vaccine_name',
            new_name='vaccine',
        ),
        migrations.RenameField(
            model_name='vaccinestock',
            old_name='vaccine_name',
            new_name='vaccine',
        ),
        migrations.AlterUniqueTogether(
            name='vaccinationpetrecord',
            unique_together={('pet', 'vaccine', 'vaccination_date')},
        ),
        migrations.AlterUniqueTogether(
            name='vaccinestock',
            unique_together={('vaccine', 'clinic')},
        ),
        migrations.AlterField(
            model_name='clinic',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='owner_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='pet',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='vaccinationpetrecord',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='vaccinestock',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
