# Generated by Codex on 2026-02-13

from django.db import migrations, models


def forwards(apps, schema_editor):
    Pet = apps.get_model('vacinacao', 'Pet')
    # owner_pet still exists at this point
    for pet in Pet.objects.all():
        if pet.owner_pet_id:
            pet.owners.add(pet.owner_pet_id)


def backwards(apps, schema_editor):
    Pet = apps.get_model('vacinacao', 'Pet')
    for pet in Pet.objects.all():
        owners = list(pet.owners.all())
        pet.owner_pet_id = owners[0].id if owners else None
        pet.save(update_fields=['owner_pet'])


class Migration(migrations.Migration):

    dependencies = [
        ('vacinacao', '0003_rename_vaccine_name_vaccinationpetrecord_vaccine_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='owners',
            field=models.ManyToManyField(related_name='pets', to='vacinacao.owner'),
        ),
        migrations.RunPython(forwards, backwards),
        migrations.RemoveField(
            model_name='pet',
            name='owner_pet',
        ),
    ]
