# Generated by Codex on 2026-02-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacinacao', '0004_pet_owners_many_to_many'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='microchip_id',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
